### ISSUE TITLE
Use CSS to create rounded images

### ISSUE THREAD

**Issue by ehsteve** [sunpy/sunpy.org#184]
Currently the mugshots on the website require the images themselves to be round with a transparent background in the non-round region. An easier solution is to use CSS to define a rounded border like so.

```css
img {
  border-radius: 50%;
}
```
